### ISSUE TITLE
Your retext-emoji have IE Fever. Please fix it;

### ISSUE THREAD

**Issue by mansres** [retextjs/retext-emoji#21]
You can check in IE browser, It is displaying emoji characters  as black and white.

**Comment by Murderlon** [comment]
Afaik this isn't really an issue with the library but rather with the OS/browser.

> To view color emoji, Windows 8.1 and above is required. — http://caniemoji.com/microsoft-windows/

Happy to reopen if you can prove otherwise :)

**Comment by wooorm** [comment]
@mansres That depends on the browser. Browsers and operating ship their own emoji. You can use https://wooorm.com/checkmoji/ to see a preview of what emoji look like on different platforms.
